use_frameworks!

platform :ios, '11.0'

target 'RCSceneKTVMusicKit_Example' do
  pod 'RCSceneKTVMusicKit'#, :path => '../'
  
  target 'RCSceneKTVMusicKit_Tests' do
    inherit! :search_paths

    
  end
end
